# Python and NumPy for Deep Learning

## 3.1 About a Python

In [1]:
import sys
# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("Hello, World!")
    print(f"Python version: {sys.version}")
else:
    print("Please use Python 3.6 or higher.")   

Hello, World!
Python version: 3.13.2 (main, Feb  5 2025, 08:05:21) [GCC 14.2.1 20250128]


## 3.2 Data Types in Python.

In [2]:
# Mutable Data Type Example (List)
my_list = [1, 2, 3]
print("Original List:", my_list)
# Modifying the list (changing contents)
my_list.append(4)
print("Modified List:", my_list)
# Immutable Data Type Example (Tuple)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)
# Trying to modify the tuple (will raise an error)
# my_tuple.append(4) # Uncommenting this line will raise an AttributeError

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


### 3.2.1 Some Common Data Types in Python:

**Numeric:**

These data types are used to represent numerical values.
- int: Represents integer values (e.g., 10, -3).
- float: Represents floating-point (decimal) values (e.g., 10.5, -2.7).
- complex: Represents complex numbers (e.g., 3 + 4j).

In [3]:
age = 23 #int
pi = 3.14 #float
temperature = -5.5 #float
print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))

data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


- **list:** Represents lists, which can contain mixed data types and are mutable (e.g., ["apple", "banana"]).

In [5]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

- **tuple:** Represents tuples, which are ordered and immutable collections (e.g., (1, 2, 3)).

In [6]:
colors = ('red', 'green', 'yellow', 'blue')
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])
colors[0] = 'purple'
colors # will generate an error as tuple is immutable.

First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


TypeError: 'tuple' object does not support item assignment

**Mapping:**

This category includes data types that store key-value pairs, allowing for efficient retrieval based on
keys.
- **dict:** Represents dictionaries, which can store various data types as values associated with unique keys (e.g., "name": "Alice", "age": 25).

In [7]:
person = {'name': 'John', 'age': 30, 'city': 'Pittsburgh'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))


Hello my name is John. I am 30 years old and I live at Pittsburgh.
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'Pittsburgh']


**Set:**

Sets are unordered collections of unique elements. They are useful for membership testing and eliminating duplicate entries.
- **set:** A mutable collection of unique items (e.g., 1, 2, 3).
- **frozenset:** An immutable version of a set (e.g., frozenset([1, 2, 3])).

In [8]:
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


**Boolean:**

This category contains types that represent truth values.
- **bool:** Represents boolean values (True or False).

In [9]:
is_student = True
has_license = False
print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


**Sequence:**

These data types are ordered collections of items. You can access elements by their position (index).
- **str:** string (str) represents sequence of characters enclosed by double quotes or single quotes.
(e.g., “Hello, World!”).It is an immutable sequence.

In [4]:
name = "Alice"
greeting = 'Hello'
address = "123 Main St"
print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))
# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])
# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letter to the fourth of the name is: lic
The first two letters of the name are: Al
Substring starting from the third letter is: ice


**Special:**

This category is used for unique data types that do not fit into the other categories.
- **NoneType:** Represents the absence of a value or a null value (e.g., None)

In [10]:
result = None

## 4.1 Exercise on Functions

### Task 1: Unit Conversion Program
Create a Python program that converts between different units of measurement.

**Requirements:**
- Prompt the user to choose the type of conversion (Length, Weight, or Volume).
- Ask the user to input the value to be converted.
- Perform the conversion and display the result.
- Use at least one function with an appropriate docstring.
- Handle potential errors (e.g., non-numeric input or unsupported conversion type) with `try-except`.

**Conversion Options:**
- **Length:** 
  - Convert meters (m) to feet (ft)
  - Convert feet (ft) to meters (m)
- **Weight:** 
  - Convert kilograms (kg) to pounds (lbs)
  - Convert pounds (lbs) to kilograms (kg)
- **Volume:** 
  - Convert liters (L) to gallons (gal)
  - Convert gallons (gal) to liters (L)

In [1]:
def convert_length(value, from_unit, to_unit):
    """Convert length between meters and feet."""
    if from_unit == 'm' and to_unit == 'ft':
        return value * 3.28084
    elif from_unit == 'ft' and to_unit == 'm':
        return value / 3.28084
    else:
        raise ValueError("Unsupported length conversion")

def convert_weight(value, from_unit, to_unit):
    """Convert weight between kilograms and pounds."""
    if from_unit == 'kg' and to_unit == 'lbs':
        return value * 2.20462
    elif from_unit == 'lbs' and to_unit == 'kg':
        return value / 2.20462
    else:
        raise ValueError("Unsupported weight conversion")

def convert_volume(value, from_unit, to_unit):
    """Convert volume between liters and gallons."""
    if from_unit == 'L' and to_unit == 'gal':
        return value * 0.264172
    elif from_unit == 'gal' and to_unit == 'L':
        return value / 0.264172
    else:
        raise ValueError("Unsupported volume conversion")

def unit_conversion():
    """Prompt user for conversion type and value, perform conversion, and display result."""
    try:
        conversion_type = input("Choose conversion type (Length, Weight, Volume): ").strip().lower()
        value = float(input("Enter the value to be converted: "))
        
        if conversion_type == 'length':
            from_unit = input("Enter the unit to convert from (m, ft): ").strip().lower()
            to_unit = input("Enter the unit to convert to (m, ft): ").strip().lower()
            result = convert_length(value, from_unit, to_unit)
        elif conversion_type == 'weight':
            from_unit = input("Enter the unit to convert from (kg, lbs): ").strip().lower()
            to_unit = input("Enter the unit to convert to (kg, lbs): ").strip().lower()
            result = convert_weight(value, from_unit, to_unit)
        elif conversion_type == 'volume':
            from_unit = input("Enter the unit to convert from (L, gal): ").strip().lower()
            to_unit = input("Enter the unit to convert to (L, gal): ").strip().lower()
            result = convert_volume(value, from_unit, to_unit)
        else:
            raise ValueError("Unsupported conversion type")
        
        print(f"Converted value: {result} {to_unit}")
    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An error occurred: {e}")

# Run the unit conversion program
unit_conversion()

Converted value: 3.28084 ft


### Task 2: Mathematical Operations on a List
Create a Python program that performs various mathematical operations on a list of numbers.

**Requirements:**
- Prompt the user to choose an operation: find the sum, average, maximum, or minimum of the numbers.
- Ask the user to input a list of numbers (separated by spaces).
- Perform the selected operation and display the result.
- Define at least one function for each operation with a proper docstring.
- Handle potential errors such as non-numeric values or empty lists.


In [2]:
def calculate_sum(numbers):
    """Calculate the sum of a list of numbers."""
    return sum(numbers)

def calculate_average(numbers):
    """Calculate the average of a list of numbers."""
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """Find the maximum value in a list of numbers."""
    return max(numbers)

def find_minimum(numbers):
    """Find the minimum value in a list of numbers."""
    return min(numbers)

def mathematical_operations():
    """Prompt user for operation type and list of numbers, perform operation, and display result."""
    try:
        operation = input("Choose an operation (sum, average, maximum, minimum): ").strip().lower()
        numbers = list(map(float, input("Enter a list of numbers (separated by spaces): ").strip().split()))
        
        if not numbers:
            raise ValueError("The list of numbers is empty")
        
        if operation == 'sum':
            result = calculate_sum(numbers)
        elif operation == 'average':
            result = calculate_average(numbers)
        elif operation == 'maximum':
            result = find_maximum(numbers)
        elif operation == 'minimum':
            result = find_minimum(numbers)
        else:
            raise ValueError("Unsupported operation type")
        
        print(f"Result: {result}")
    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An error occurred: {e}")

# Run the mathematical operations program
mathematical_operations()

Result: 60.0


## 4.2 Exercise on List Manipulation

Implement the following functions:


1. **Extract Every Other Element**  
   Define a function `extract_every_other(lst)` that returns a new list containing every other element from `lst`.  
   *Example:* For `[1, 2, 3, 4, 5, 6]`, the output should be `[1, 3, 5]`.

In [3]:
def extract_every_other(lst):
    """Return a new list containing every other element from the input list."""
    return lst[::2]

# Example usage
example_list = [1, 2, 3, 4, 5, 6]
print(extract_every_other(example_list))  # Output: [1, 3, 5]

[1, 3, 5]


2. **Slice a Sublist**  
   Define a function `get_sublist(lst, start, end)` that returns the sublist from index `start` to `end` (inclusive).  
   *Example:* For `[1, 2, 3, 4, 5, 6]` with `start=2` and `end=4`, the output should be `[3, 4, 5]`.

In [4]:
def get_sublist(lst, start, end):
    """Return the sublist from index start to end (inclusive)."""
    return lst[start:end+1]

# Example usage
start = 2
end = 4
print(get_sublist(example_list, start, end))  # Output: [3, 4, 5]

[3, 4, 5]


3. **Reverse a List Using Slicing**  
   Define a function `reverse_list(lst)` that returns the reversed list using slicing.  
   *Example:* For `[1, 2, 3, 4, 5]`, the output should be `[5, 4, 3, 2, 1]`.

In [6]:
def reverse_list(lst):
    """Return the reversed list using slicing."""
    return lst[::-1]

# Example usage
print(reverse_list([1, 2, 3, 4, 5]))  # Output: [5, 4, 3, 2, 1]

[5, 4, 3, 2, 1]


4. **Remove the First and Last Elements**  
   Define a function `remove_first_last(lst)` that returns a sublist without the first and last elements.  
   *Example:* For `[1, 2, 3, 4, 5]`, the output should be `[2, 3, 4]`.

In [1]:
def remove_first_last(lst):
    """Return a sublist without the first and last elements."""
    return lst[1:-1]

# Example usage
print(remove_first_last([1, 2, 3, 4, 5]))  # Output: [2, 3, 4]

[2, 3, 4]


5. **Get the First n Elements**  
   Define a function `get_first_n(lst, n)` that returns the first `n` elements of `lst`.  
   *Example:* For `[1, 2, 3, 4, 5]` with `n=3`, the output should be `[1, 2, 3]`.

In [2]:
def get_first_n(lst, n):
    """Return the first n elements of the input list."""
    return lst[:n]

# Example usage
print(get_first_n([1, 2, 3, 4, 5], 3))  # Output: [1, 2, 3]

[1, 2, 3]


6. **Extract Elements from the End**  
   Define a function `get_last_n(lst, n)` that returns the last `n` elements of `lst`.  
   *Example:* For `[1, 2, 3, 4, 5]` with `n=2`, the output should be `[4, 5]`.

In [3]:
def get_last_n(lst, n):
    """Return the last n elements of the input list."""
    return lst[-n:]

# Example usage
print(get_last_n([1, 2, 3, 4, 5], 2))  # Output: [4, 5]

[4, 5]


7. **Extract Elements in Reverse Order (Skipping One)**  
   Define a function `reverse_skip(lst)` that returns a new list containing every second element in reverse order starting from the second-to-last element.  
   *Example:* For `[1, 2, 3, 4, 5, 6]`, the output should be `[5, 3, 1]`.

In [4]:
def reverse_skip(lst):
    """Return a new list containing every second element in reverse order starting from the second-to-last element."""
    return lst[-2::-2]

# Example usage
print(reverse_skip([1, 2, 3, 4, 5, 6]))  # Output: [5, 3, 1]

[5, 3, 1]


## 4.3 Exercise on Nested Lists

Implement the following functions to work with nested lists:


1. **Flatten a Nested List**  
   Define a function `flatten(lst)` that takes a nested list and returns a single flattened list.  
   *Example:* For `[[1, 2], [3, 4], [5]]`, the output should be `[1, 2, 3, 4, 5]`.


In [2]:
def flatten(lst):
    """Return a single flattened list from a nested list."""
    return [item for sublist in lst for item in sublist]

# Example usage
nested_list = [[1, 2], [3, 4], [5]]
print(flatten(nested_list))  # Output: [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]


2. **Accessing Nested List Elements**  
   Define a function `access_nested_element(lst, indices)` that returns the element at the position specified by `indices`.  
   *Example:* For `lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]` with `indices = [1, 2]`, the output should be `6`.

In [6]:
def access_nested_element(lst, indices):
    """Return the element at the position specified by indices in a nested list."""
    element = lst
    for index in indices:
        element = element[index]
    return element

# Example usage
indices = [1, 1]
print(access_nested_element(nested_list, indices))  # Output: 4

4


3. **Sum of All Elements in a Nested List**  
   Define a function `sum_nested(lst)` that returns the sum of all numbers in the nested list, regardless of its depth.  
   *Example:* For `[[1, 2], [3, [4, 5]], 6]`, the output should be `21`.


In [1]:
def sum_nested(lst):
    """Return the sum of all numbers in the nested list, regardless of its depth."""
    total = 0
    for element in lst:
        if isinstance(element, list):
            total += sum_nested(element)
        else:
            total += element
    return total

# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nested_list))  # Output: 21

21


4. **Remove Specific Element from a Nested List**  
   Define a function `remove_element(lst, elem)` that removes all occurrences of `elem` from the nested list and returns the modified list.  
   *Example:* For `lst = [[1, 2], [3, 2], [4, 5]]` with `elem = 2`, the output should be `[[1], [3], [4, 5]]`.

In [3]:
def remove_element(lst, elem):
    """Remove all occurrences of elem from the nested list and return the modified list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

# Example usage
elem_to_remove = 2
print(remove_element(nested_list, elem_to_remove))  # Output: [[1], [3], [4, 5]]

[[1], [3, [4, 5]], 6]


5. **Find the Maximum Element in a Nested List**  
   Define a function `find_max(lst)` that returns the maximum element in the nested list.  
   *Example:* For `[[1, 2], [3, [4, 5]], 6]`, the output should be `6`.

In [4]:
def find_max(lst):
    """Return the maximum element in the nested list."""
    max_elem = float('-inf')
    for element in lst:
        if isinstance(element, list):
            max_elem = max(max_elem, find_max(element))
        else:
            max_elem = max(max_elem, element)
    return max_elem

# Example usage
print(find_max(nested_list))  # Output: 6

6


6. **Count Occurrences of an Element in a Nested List**  
   Define a function `count_occurrences(lst, elem)` that counts how many times `elem` appears in the nested list.  
   *Example:* For `lst = [[1, 2], [2, 3], [2, 4]]` with `elem = 2`, the output should be `3`.

In [5]:
def count_occurrences(lst, elem):
    """Count how many times elem appears in the nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

# Example usage
print(count_occurrences(nested_list, elem_to_remove))  # Output will depend on the actual structure of nested_list

1


7. **Deep Flatten a List**  
   Define a function `deep_flatten(lst)` that flattens a list of lists of lists into a single list regardless of depth.  
   *Example:* For `[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]`, the output should be `[1, 2, 3, 4, 5, 6, 7, 8]`.

In [6]:
def deep_flatten(lst):
    """Flatten a list of lists of lists into a single list regardless of depth."""
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

# Example usage
nested_list_example = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(nested_list_example))  # Output: [1, 2, 3, 4, 5, 6, 7, 8]

[1, 2, 3, 4, 5, 6, 7, 8]


8. **Nested List Average**  
   Define a function `average_nested(lst)` that returns the average of all elements in the nested list.  
   *Example:* For `[[1, 2], [3, 4], [5, 6]]`, the output should be `3.5`.

In [7]:
def average_nested(lst):
    """Return the average of all elements in the nested list."""
    def flatten(lst):
        """Helper function to flatten the nested list."""
        flat_list = []
        for item in lst:
            if isinstance(item, list):
                flat_list.extend(flatten(item))
            else:
                flat_list.append(item)
        return flat_list
    
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list)

# Example usage
nested_list_example = [[1, 2], [3, 4], [5, 6]]
print(average_nested(nested_list_example))  # Output: 3.5

3.5


# 10 To - Do - NumPy
Please complete all the problems listed below:

## 10.1 Basic Vector and Matrix Operation with Numpy.
### Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [11]:
import numpy as np

# 1. Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("Empty array (2x2):\n", empty_array)

# 2. Initialize an all one array with size 4X2
ones_array = np.ones((4, 2))
print("All ones array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
fill_value = 7
filled_array = np.full((3, 3), fill_value)
print("Array filled with value 7 (3x3):\n", filled_array)

# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(given_array)
print("Zeros like given array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("Ones like given array:\n", ones_like_array)

# 6. For an existing list new_list = [1, 2, 3, 4] convert to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Numpy array from list:\n", numpy_array)

Empty array (2x2):
 [[1.33859652e-313 0.00000000e+000]
 [6.88056762e-310 5.48289134e-310]]
All ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array filled with value 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros like given array:
 [[0 0 0]
 [0 0 0]]
Ones like given array:
 [[1 1 1]
 [1 1 1]]
Numpy array from list:
 [1 2 3 4]


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [12]:
# 1. Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)
print("Array with values ranging from 10 to 49:\n", array_10_to_49)

# 2. Create a 3X3 matrix with values ranging from 0 to 8
matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("3x3 matrix with values ranging from 0 to 8:\n", matrix_0_to_8)

# 3. Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_random_array = random_array.mean()
print("Random array of size 30:\n", random_array)
print("Mean of the random array:", mean_random_array)

# 5. Create a 10X10 array with random values and find the minimum and maximum values
random_10x10_array = np.random.random((10, 10))
min_value = random_10x10_array.min()
max_value = random_10x10_array.max()
print("10x10 array with random values:\n", random_10x10_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero array with 5th element replaced by 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print("Reversed array:\n", reversed_arr)

# 8. Create a 2d array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D array with 1 on border and 0 inside:\n", border_array)

# 9. Create a 8X8 matrix and fill it with a checkerboard pattern
checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print("8x8 checkerboard pattern:\n", checkerboard_matrix)

Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array of size 30:
 [0.27977983 0.30948964 0.13568135 0.76221876 0.55533159 0.27642914
 0.16312746 0.163742   0.48794209 0.63255422 0.96548442 0.32708062
 0.2080198  0.13387099 0.00867756 0.46711549 0.92537596 0.12972994
 0.26103058 0.77949128 0.93809577 0.90370736 0.11484834 0.3946289
 0.92758238 0.58202057 0.43189988 0.45814964 0.93600864 0.88753948]
Mean of the random array: 0.4848884569037732
10x10 array with random values:
 [[0.74284213 0.57215562 0.92234313 0.53883397 0.99271722 0.37996501
  0.85688648 0.03355287 0.1720444  0.43977647]
 [0.592299   0.1791038  0.24472769 0.86166027 0.57554609 0.22416028
  0.44935164 0.1511157  0.65834083 0.62288374]
 [0.51010996 0.93137449 0.15664551

### Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.{Hint:try np.concatenate() or np.vstack() functions.}
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [13]:
# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("Addition of x and y:\n", add_xy)

# 2. Subtract the two arrays
subtract_xy = x - y
print("Subtraction of x and y:\n", subtract_xy)

# 3. Multiply the array with any integers of your choice
multiply_x = x * 3
print("Multiplication of x with 3:\n", multiply_x)

# 4. Find the square of each element of the array
square_x = x ** 2
print("Square of each element in x:\n", square_x)

# 5. Find the dot product between: v and w; x and v; x and y
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

# 6. Concatenate x and y along row and Concatenate v and w along column
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))
print("Concatenation of x and y along rows:\n", concat_xy_row)
print("Concatenation of v and w along columns:\n", concat_vw_col)

# 7. Concatenate x and v; if you get an error, observe and explain why did you get the error?
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v along rows:\n", concat_xv)
except ValueError as e:
    print("Error:", e)
    print("Explanation: The arrays x and v cannot be concatenated along rows because they have different dimensions.")

Addition of x and y:
 [[ 6  8]
 [10 13]]
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]
Square of each element in x:
 [[ 1  4]
 [ 9 25]]
Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: The arrays x and v cannot be concatenated along rows because they have different dimensions.


### Problem - 4: Matrix Operations:
- For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)
T = BTAT

- Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

- Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}

In [14]:
import numpy as np

# Define the arrays A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A−1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1:\n", identity_matrix)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
print("AB == BA:", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T A^T
AB_T = np.transpose(AB)
B_T = np.transpose(B)
A_T = np.transpose(A)
BT_AT = np.dot(B_T, A_T)
print("(AB)^T:\n", AB_T)
print("B^T A^T:\n", BT_AT)
print("(AB)^T == B^T A^T:", np.array_equal(AB_T, BT_AT))

# Solve the system of linear equations using Inverse Methods
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# Represent the equations in matrix form AX = B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve for X using np.linalg.inv
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)
print("Solution using inverse method:\n", X)

# Solve the system using np.linalg.solve
X_solve = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve:\n", X_solve)

A * A^-1:
 [[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA: False
(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
(AB)^T == B^T A^T: True
Solution using inverse method:
 [ 2.  1. -2.]
Solution using np.linalg.solve:
 [ 2.  1. -2.]


## 10.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays. Follow the instructions:

**1. Element-wise Addition:**
- Using **Python Lists**, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
- Using **Numpy Arrays**, Repeat the calculation and measure and print the time taken for
this operation.

In [17]:
import time

# Create two lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Measure time for element-wise addition using Python lists
start_time = time.time()
list_sum = [a + b for a, b in zip(list1, list2)]
end_time = time.time()
print("Time taken for element-wise addition using Python lists:", end_time - start_time)

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Measure time for element-wise addition using NumPy arrays
start_time = time.time()
array_sum = array1 + array2
end_time = time.time()
print("Time taken for element-wise addition using NumPy arrays:", end_time - start_time)

Time taken for element-wise addition using Python lists: 0.1181941032409668
Time taken for element-wise addition using NumPy arrays: 0.0030350685119628906


**2. Element-wise Multiplication**
- Using **Python Lists**, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
- Using **Numpy Arrays**, Repeat the calculation and measure and print the time taken for
this operation.

In [18]:
# Create two lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Measure time for element-wise multiplication using Python lists
start_time = time.time()
list_product = [a * b for a, b in zip(list1, list2)]
end_time = time.time()
print("Time taken for element-wise multiplication using Python lists:", end_time - start_time)

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Measure time for element-wise multiplication using NumPy arrays
start_time = time.time()
array_product = array1 * array2
end_time = time.time()
print("Time taken for element-wise multiplication using NumPy arrays:", end_time - start_time)

Time taken for element-wise multiplication using Python lists: 0.09625101089477539
Time taken for element-wise multiplication using NumPy arrays: 0.0014586448669433594


**3. Dot Product**
- Using **Python Lists**, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
- Using **Numpy Arrays**, Repeat the calculation and measure and print the time taken for
this operation.

In [20]:
# Create two lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Measure time for dot product using Python lists
start_time = time.time()
dot_product_list = sum(a * b for a, b in zip(list1, list2))
end_time = time.time()
print("Dot product using Python lists:", dot_product_list)
print("Time taken for dot product using Python lists:", end_time - start_time)

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Measure time for dot product using NumPy arrays
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
print("Dot product using NumPy arrays:", dot_product_array)
print("Time taken for dot product using NumPy arrays:", end_time - start_time)

Dot product using Python lists: 333332833333500000
Time taken for dot product using Python lists: 0.10161566734313965
Dot product using NumPy arrays: 333332833333500000
Time taken for dot product using NumPy arrays: 0.0017070770263671875


**4. Matrix Multiplication**
- Using **Python lists**, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
- Using **NumPy arrays**, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [21]:
# Create two 1000x1000 matrices using Python lists
matrix1_list = [[i + j for j in range(1000)] for i in range(1000)]
matrix2_list = [[i - j for j in range(1000)] for i in range(1000)]

# Measure time for matrix multiplication using Python lists
start_time = time.time()
result_list = [[sum(a * b for a, b in zip(matrix1_row, matrix2_col)) for matrix2_col in zip(*matrix2_list)] for matrix1_row in matrix1_list]
end_time = time.time()
print("Time taken for matrix multiplication using Python lists:", end_time - start_time)

# Create two 1000x1000 matrices using NumPy arrays
matrix1_np = np.array(matrix1_list)
matrix2_np = np.array(matrix2_list)

# Measure time for matrix multiplication using NumPy arrays
start_time = time.time()
result_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print("Time taken for matrix multiplication using NumPy arrays:", end_time - start_time)

Time taken for matrix multiplication using Python lists: 102.25621938705444
Time taken for matrix multiplication using NumPy arrays: 1.5844590663909912
